"use client";
import {useState} from 'react';
import Brand from './brand';
import {ShieldCheck,Eye,EyeOff} from 'lucide-react';
export default function AdminLogin({loading=false}:{loading?:boolean}){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const result=await r.json() as {error?:string};if(!r.ok)throw Error(result.error||'Unable to log in.');window.location.assign('/admin');}catch(e){setError(e instanceof Error?e.message:'Unable to log in.');setBusy(false);}}
 return <main className="loginpage"><Brand/><section className="logincard"><div className="loginshield"><ShieldCheck size={28}/></div><p className="eyebrow">DATASCOUT ADMIN</p><h1>Welcome back.</h1><p>Log in to manage reseller prices and data plans.</p>{loading?<p role="status">Checking your session…</p>:<form className="loginform" onSubmit={login}><label htmlFor="admin-username">Username</label><input id="admin-username" autoComplete="username" required maxLength={100} value={username} onChange={e=>setUsername(e.target.value)} autoFocus/><label htmlFor="admin-password">Password</label><div className="passwordfield"><input id="admin-password" autoComplete="current-password" type={visible?'text':'password'} required maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{error&&<p className="loginerror" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Logging in…':'Log in'}</button></form>}<div className="logininfo"><ShieldCheck size={16}/><span>Admin access only. Your session ends when you log out.</span></div><a className="loginback" href="/">Back to DataScout</a></section></main>
}
