"use client";
import {AdSpace,AdvertisingManager} from "./advertising";
import {Advertisement} from "@/lib/ad-slots";
import Brand from "./brand";
import AdminLogin from "./admin-login";
import { PLAN_TYPES } from "@/lib/plan-types";
import {useState,useEffect} from "react";
import {ArrowUpRight,Search,SlidersHorizontal,ArrowRight,Check,Plus,X,Wifi,ShieldCheck,BarChart3} from "lucide-react";
type Plan={id:string;reseller:string;network:string;gb:number;price:number;days:number;type:string;url:string;updated:string;sourceUrl?:string;checkedAt?:string;tier?:string;label?:string;notes?:string};
const blank={reseller:"",network:"MTN",gb:1,price:0,days:30,type:"SME",url:"",sourceUrl:"",tier:"",label:"",notes:"",checkedAt:""};
const money=(n:number)=>`₦${n.toLocaleString("en-NG",{maximumFractionDigits:2})}`;
export default function Scout({admin:initialAdmin=false,initialPlans,initialError=""}:{admin?:boolean;initialPlans?:Plan[];initialError?:string}){
 const admin=initialAdmin;
 const [ads,setAds]=useState<Advertisement[]>([]);
 useEffect(()=>{if(!admin)fetch("/api/ads",{cache:"no-store"}).then(r=>r.ok?r.json():[]).then(b=>setAds(b as Advertisement[])).catch(()=>{})},[admin]);
 const [authorized,setAuthorized]=useState<boolean|null>(null);
 useEffect(()=>{if(admin){setAuthorized(null);fetch('/api/admin-session',{cache:'no-store'}).then(r=>r.json()).then(b=>setAuthorized(!!(b as {authorized:boolean}).authorized)).catch(()=>setAuthorized(false));}},[admin]);
 
 const [rows,setRows]=useState<Plan[]>(initialPlans||[]),[loading,setLoading]=useState(initialPlans===undefined&&!initialError),[error,setError]=useState(initialError),[network,setNetwork]=useState("All networks"),[size,setSize]=useState("All sizes"),[validity,setValidity]=useState("Any validity"),[type,setType]=useState("All types"),[query,setQuery]=useState(""),[sort,setSort]=useState("unit"),[selected,setSelected]=useState<string[]>([]),[compare,setCompare]=useState(false),[editing,setEditing]=useState(false),[form,setForm]=useState<any>(blank),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 async function load(){try{const r=await fetch('/api/plans');if(!r.ok)throw Error();setRows(await r.json());setError("");}catch{setError("Could not load saved plans. Please try again.");}finally{setLoading(false)}}
 useEffect(()=>{if(initialPlans===undefined)load()},[]);
 useEffect(()=>{const elements=document.querySelectorAll('.reveal');if(!('IntersectionObserver' in window)){elements.forEach(e=>e.classList.add('visible'));return;}const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:0.08});elements.forEach(e=>observer.observe(e));return()=>observer.disconnect()},[admin,authorized,loading]);
 const source=rows;
 const filtered=source.filter(p=>(network==="All networks"||p.network===network)&&(size==="All sizes"||p.gb===Number(size))&&(type==="All types"||p.type===type)&&(validity==="Any validity"||p.days===Number(validity))&&`${p.reseller} ${p.network}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="unit"?a.price/a.gb-b.price/b.gb:sort==="price"?a.price-b.price:b.gb-a.gb);
 const picks=source.filter(p=>selected.includes(p.id));
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<3?[...s,id]:s)}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice("");try{const r=await fetch('/api/plans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const b=await r.json() as {error?:string};if(!r.ok)throw Error(b.error);await load();setEditing(false);setNotice("Plan saved successfully.")}catch(e){setNotice(e instanceof Error?e.message:"Unable to save")}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm("Delete this plan?"))return;setBusy(true);try{const r=await fetch('/api/plans',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(!r.ok)throw Error();await load();setNotice("Plan deleted.")}catch{setNotice("Could not delete this plan.")}finally{setBusy(false)}}
 async function logout(){setBusy(true);setNotice('');try{const r=await fetch('/api/admin/logout',{method:'POST'});if(!r.ok)throw Error();window.location.assign('/admin/login');}catch{setNotice('Could not log out. Please try again.');setBusy(false);}}
 if(admin && authorized!==true)return <AdminLogin loading={authorized===null}/>;
 return <><header className="header"><Brand/><nav><a href="/#plans" className={!admin?'active':''}>Compare plans</a><a href="/#how">How it works</a></nav>{admin&&<a className="adminlink" href="/">View website</a>}</header>
 <main>{admin?<section className="adminhero"><p className="eyebrow">DATASCOUT / MANAGEMENT</p><h1>Your plans. In one place.</h1><p>Add verified reseller prices, update plans, and manage referral links.</p><p><ShieldCheck size={14} style={{display:"inline",verticalAlign:"middle",marginRight:6}}/>Authorized admin session · Changes require an active admin session.</p><p><button className="logoutbutton" disabled={busy} onClick={logout}>Log out</button></p><div className="adminstats"><div><strong>{rows.length}</strong><span>Published plans</span></div><div><strong>{new Set(rows.map(p=>p.reseller)).size}</strong><span>Resellers</span></div><div><strong>{new Set(rows.map(p=>p.network)).size}</strong><span>Networks covered</span></div><button className="primary" onClick={()=>{setForm(blank);setEditing(true);setNotice("")}}><Plus size={18}/>Add a plan</button></div></section>:<section className="hero"><div className="herocopy"><p className="eyebrow"><span/> THE SMARTER WAY TO BUY DATA</p><h1>Same network.<br/>Better <em>data deals.</em></h1><p>Compare data reseller prices in one place.<br/>Find a plan that fits your budget, then buy directly from the reseller.</p><a className="primary" href="#plans">Find my next plan<ArrowRight size={19}/></a><div className="heroquickstats"><span><strong>{loading?"…":rows.length}</strong> listed plans</span><span><strong>{loading?"…":new Set(rows.map(p=>p.reseller)).size}</strong> resellers</span><span className="checkedchip"><Check size={13}/>Price sources included</span></div><div className="heronote"><ShieldCheck size={16}/>Clear comparisons. No checkout on DataScout.</div></div><div className="heroart" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="floating floatingone"><span className="network MTN">M</span><div>MTN <small>Compare your options</small></div><Check size={17}/></div><div className="signalcard"><div className="signalhead"><Wifi size={20}/><span>YOUR NEXT CONNECTION</span><span className="dot"/></div><div className="bigdata">5<span>GB</span></div><div className="bars">{[28,45,38,65,52,83,68,96].map((h,i)=><i key={i} style={{height:h}}/>)}</div><div className="signalfoot">More possibilities.<br/><strong>Less guesswork.</strong><ArrowUpRight size={32}/></div></div><div className="floating floatingtwo"><span className="network Airtel">A</span><div>Airtel <small>Find your fit</small></div><ArrowUpRight size={18}/></div><span className="artlabel">ONE PLACE. ALL YOUR OPTIONS.</span></div></section>}
 {!admin&&<div className="networkstrip"><span>Explore Nigeria’s networks</span><strong><i className="minidot MTN"/>MTN</strong><strong><i className="minidot Airtel"/>airtel</strong><strong><i className="minidot Glo"/>glo</strong><strong><i className="minidot nine"/>9mobile</strong></div>}
 {!admin&&<AdSpace slot="top" ads={ads}/>}
 {admin&&<AdvertisingManager/>}
 <section className="planssection reveal" id="plans"><div className="sectionheading"><div><p className="eyebrow">{admin?'YOUR CATALOGUE':'FIND YOUR FIT'}</p><h2>{admin?'Manage data plans':'A better deal starts here.'}</h2><p>{admin?'Your saved plans appear on the comparison page.':'Filter by network, compare prices, and choose what works for you.'}</p></div>{!admin&&<span className="pill"><BarChart3 size={16}/>Compare up to 3 plans</span>}</div>
 {!admin&&<><div className="cataloguebanner"><span className="bannericon"><BarChart3 size={19}/></span><div><strong>Public prices. Clear comparisons.</strong><p>Website-sourced and submitted prices are labelled separately. Submitted CSV listings have not been independently verified; missing links and validity are marked as not supplied.</p></div></div><div className="networktabs" aria-label="Choose network">{['All networks','MTN','Airtel','Glo','9mobile'].map(n=><button key={n} className={network===n?'selected':''} data-network={n} onClick={()=>setNetwork(n)}><span className={`tabdot ${n}`}/>{n}<small>{n==='All networks'?source.length:source.filter(p=>p.network===n).length}</small></button>)}</div></>}
 <div className="filters"><div className="searchbox"><Search size={18}/><input aria-label="Search resellers" placeholder="Search a reseller..." value={query} onChange={e=>setQuery(e.target.value)}/></div><label>Network<select value={network} onChange={e=>setNetwork(e.target.value)}>{["All networks","MTN","Airtel","Glo","9mobile"].map(s=><option key={s}>{s}</option>)}</select></label><label>Data size<select value={size} onChange={e=>setSize(e.target.value)}><option>All sizes</option>{[...new Set(source.map(p=>p.gb))].sort((a,b)=>a-b).map(s=><option value={s} key={s}>{s} GB</option>)}</select></label><label>Plan type<select value={type} onChange={e=>setType(e.target.value)}>{["All types",...PLAN_TYPES].map(s=><option key={s}>{s}</option>)}</select></label><label>Validity<select value={validity} onChange={e=>setValidity(e.target.value)}><option>Any validity</option>{[...new Set(source.map(p=>p.days))].sort((a,b)=>a-b).map(d=><option key={d} value={d}>{d?`${d} days`:'Not supplied'}</option>)}</select></label><button className="reset" onClick={()=>{setQuery("");setNetwork("All networks");setSize("All sizes");setType("All types");setValidity("Any validity")}}>Reset</button></div>
 <div className="resultsbar"><span>{loading?'Loading plans…':`${filtered.length} plans found`}</span><label><SlidersHorizontal size={15}/>Sort by <select aria-label="Sort plans" value={sort} onChange={e=>setSort(e.target.value)}><option value="unit">Lowest price / GB</option><option value="price">Lowest total price</option><option value="size">Largest data size</option></select></label></div>
 {error&&<p role="alert" className="demo">{error} <button onClick={load}>Retry</button></p>}{notice&&<p role="status" className="demo">{notice}</p>}
 <div className="tablewrap"><table><thead><tr>{!admin&&<th>Select</th>}<th>Reseller</th><th>Network</th><th>Data plan</th><th>Validity</th><th>Price <small>/ GB</small></th><th>Total price</th><th/></tr></thead><tbody>{filtered.map((p,i)=><tr key={p.id} className={selected.includes(p.id)?"selectedrow":""}>{!admin&&<td><input type="checkbox" aria-label={`Compare ${p.reseller} ${p.network} ${p.gb} GB`} checked={selected.includes(p.id)} disabled={!selected.includes(p.id)&&selected.length===3} onChange={()=>toggle(p.id)}/></td>}<td><div className="reseller"><span className="resellericon" data-reseller={p.reseller}>{p.reseller.split(' ').filter(Boolean).slice(0,2).map(s=>s[0]).join('')}</span><div><strong>{p.reseller}</strong><small>{p.tier?`${p.tier} price`:"Admin-listed price"}</small>{p.sourceUrl&&<a className="sourcebadge" href={p.sourceUrl} target="_blank" rel="noopener noreferrer">Price source ↗</a>}</div></div></td><td><span className={`networkbadge ${p.network}`}>{p.network}</span></td><td><strong>{p.gb} GB</strong><small className="block">{p.type}</small>{p.label&&<small className="block plannotes">{p.label}</small>}</td><td>{p.days?`${p.days} days`:'Not supplied'}</td><td>{money(p.price/p.gb)}</td><td><strong className="total">{money(p.price)}</strong>{i===0&&sort==="unit"&&<small className="best">Lowest / GB</small>}</td><td>{admin?<div className="rowactions"><button onClick={()=>{setForm(p);setEditing(true);setNotice("")}}>Edit</button><button disabled={busy} onClick={()=>remove(p.id)}>Delete</button></div>:p.url?<a className="visit" href={p.url} target="_blank" rel="noopener noreferrer sponsored">Visit reseller<ArrowUpRight size={15}/></a>:<span className="exampletag">Link not supplied</span>}</td></tr>)}</tbody></table>{!loading&&!filtered.length&&<div className="empty"><Search size={30}/><h3>{admin&&!rows.length?'Start your catalogue':'No matching plans'}</h3><p>{admin&&!rows.length?'Add your first verified reseller plan above.':'Try a different network or reset the filters.'}</p></div>}</div>
 {!admin&&<p className="footnote">Prices are not live feeds. Submitted CSV prices are unverified. Account registration may be required. Plan types and eligibility can differ. Confirm price, validity and delivery terms with the reseller before paying. Referral links may earn DataScout a commission.</p>}</section>
 {!admin&&<AdSpace slot="middle" ads={ads}/>}
 {!admin&&<><section className="how reveal" id="how"><div><p className="eyebrow">LESS SEARCHING. MORE CONNECTING.</p><h2>Three steps to your<br/>next data plan.</h2></div><div className="steps">{[['01','Choose your network','Select a network and the data size you need.'],['02','Compare your options','Check the total price, cost per GB and plan type.'],['03','Buy from the reseller','Follow their link and confirm the details before buying.']].map(([n,t,d])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section></>}
 {!admin&&<AdSpace slot="bottom" ads={ads}/>}
 </main><footer><Brand priority={false}/><p>Make every gigabyte count.</p><small>© {new Date().getFullYear()} DataScout · Nigeria</small></footer>
 {!admin&&selected.length>0&&<div className="comparebar"><span><strong>{selected.length} / 3</strong> plans selected</span><button onClick={()=>setSelected([])}>Clear</button><button className="primary" disabled={selected.length<2} onClick={()=>setCompare(true)}>Compare plans<ArrowRight size={17}/></button></div>}
 {compare&&<div className="overlay" onClick={()=>setCompare(false)}><div className="modal comparemodal" role="dialog" aria-modal="true" aria-label="Compare plans" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close comparison" onClick={()=>setCompare(false)}><X/></button><p className="eyebrow">SIDE BY SIDE</p><h2>Which plan fits you?</h2><div className="comparison">{picks.map(p=><article key={p.id}><span className={`networkbadge ${p.network}`}>{p.network}</span><h3>{p.reseller}</h3><div className="comparegb">{p.gb} GB</div><strong>{money(p.price)}</strong><dl><dt>Price per GB</dt><dd>{money(p.price/p.gb)}</dd><dt>Validity</dt><dd>{p.days?`${p.days} days`:'Not supplied'}</dd><dt>Plan type</dt><dd>{p.type}</dd><dt>Price tier</dt><dd>{p.tier||"Admin-listed"}</dd>{p.checkedAt&&<><dt>Source checked</dt><dd>{new Date(p.checkedAt).toLocaleDateString("en-NG")}</dd></>}</dl>{p.notes&&<p className="footnote">{p.notes}</p>}{p.sourceUrl&&<a className="sourcebadge" href={p.sourceUrl} target="_blank" rel="noopener noreferrer">See price source ↗</a>}{p.url?<a className="primary" href={p.url} target="_blank" rel="noopener noreferrer sponsored">Visit reseller<ArrowUpRight size={16}/></a>:<p className="footnote">Reseller link not supplied.</p>}</article>)}</div></div></div>}
 {editing&&<div className="overlay"><form className="modal" role="dialog" aria-modal="true" aria-label="Plan editor" onSubmit={save}><button type="button" className="close" aria-label="Close editor" onClick={()=>setEditing(false)}><X/></button><p className="eyebrow">CATALOGUE EDITOR</p><h2>{form.id?'Update plan':'Add a verified plan'}</h2><p className="footnote">Enter the price and any confirmed details. Leave validity or website blank if not supplied.</p><div className="formgrid">{[['reseller','Reseller name','text'],['gb','Data size (GB)','number'],['price','Total price (₦)','number'],['days','Validity (days, optional)','number'],['url','Website / referral URL (optional)','url'],['sourceUrl','Price source URL (optional)','url'],['tier','Price tier (e.g. Regular)','text'],['label','Plan label / extras (optional)','text']].map(([key,label,kind])=><label key={key} className={key==='url'?'full':''}>{label}<input required={!['sourceUrl','tier','label','days','url'].includes(key)} type={kind==='url'?'text':kind} inputMode={key==='url'?'url':undefined} placeholder={key==='url'?'reseller.com or https://reseller.com':undefined} min={key==='days'?1:kind==='number'?0.01:undefined} max={key==='days'?365:undefined} step={key==='days'?1:kind==='number'?0.01:undefined} value={key==='days'&&!form.days?"":form[key]??""} onChange={e=>setForm({...form,[key]:kind==='number'?Number(e.target.value):e.target.value})}/></label>)}<label>Network<select value={form.network} onChange={e=>setForm({...form,network:e.target.value})}>{['MTN','Airtel','Glo','9mobile'].map(v=><option key={v}>{v}</option>)}</select></label><label>Plan type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{PLAN_TYPES.map(v=><option key={v}>{v}</option>)}</select></label><label className="full">Notes (optional)<textarea value={form.notes||""} maxLength={300} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label className="full">Price source checked<input type="date" value={form.checkedAt?form.checkedAt.slice(0,10):""} onChange={e=>setForm({...form,checkedAt:e.target.value})}/></label></div>{notice&&<p role="alert">{notice}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save plan'}<Check size={17}/></button></form></div>}
 </>;
}
